class Animations

  def initialize(computer_board, user_board)
    @gameplay = Gameplay.new
    @computer_board = computer_board
    @user_board = user_board
  end

  def ship_screen
    puts "\e[H\e[2J"
    puts "\n"
    puts "\n"
    puts "          __   _           __   _              __   _"
    puts "        _(  )_( )_       _(  )_( )_          _(  )_( )_"
    puts "       (_   _    _)     (_   _    _)       (_   _    _)"
    puts "         (_) (__)         (_) (__)           (_) (__)"
    puts "\n"
    puts "\n"
    puts "               ,,=================================.."
    puts "              //   _ _   _ _   _ _   _ _   _ _   _ ]]"
    puts "        ..___//                                    }}"
    puts "      //                                           ]]"
    puts "     // = = = = = = = = SHIP INFORMATION = = = = = \\\\"
    puts "       --------              __-_ _-    _-___ _-    ]]"
    puts "               \\\\          //   \\\\     //   \\\\      ]]"
    puts "                \\\\ =================================="
    puts "          \"_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"("
    puts "\n"
  end

  def display_boards(computer_board, user_board)
    puts "\n\n"
    puts "    =============COMPUTER BOARD============="
    puts @computer_board.render(true)
    puts "\n"
    puts "    ==============PLAYER BOARD=============="
    puts @user_board.render(true)
    puts "\n\n\n\n"
  end

  def splode
    8.times do
      puts "         |"
      sleep(0.11)
    end
    puts "      'Splode'     "
    sleep(2)
  end

  def warning_incoming
    print "    "
    39.times do
      print "-"
      sleep(0.03)
    end
  print "\n"
  end

  def ending(message)
    puts "\e[H\e[2J"
    puts "\n"
    puts "\n"
    puts "          __   _           __   _              __   _"
    puts "        _(  )_( )_       _(  )_( )_          _(  )_( )_"
    puts "       (_   _    _)     (_   _    _)       (_   _    _)"
    puts "         (_) (__)         (_) (__)           (_) (__)"
    puts "\n"
    puts "\n                      #{message}"
    puts "               ,,=================================.."
    puts "              //   _ _   _ _   _ _   _ _   _ _   _ ]]"
    puts "        ..___//                                    }}"
    puts "      //                                           ]]"
    puts "     // = = = = = = = = = = = = = = = = = = = = = = \\\\"
    puts "       --------              __-_ _-    _-___ _-    ]]"
    puts "               \\\\          //   \\\\     //   \\\\      ]]"
    puts "                \\\\ =================================="
    puts "       \"_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"("
    puts "\n"
    sleep(0.5)
    puts "\e[H\e[2J"
    puts "\n"
    puts "\n"
    puts "          __   _           __   _              __   _"
    puts "        _(  )_( )_       _(  )_( )_          _(  )_( )_"
    puts "       (_   _    _)     (_   _    _)       (_   _    _)"
    puts "         (_) (__)         (_) (__)           (_) (__)"
    puts "\n"
    puts "\n                      #{message}"
    puts "\n"
    puts "               ,,=================================.."
    puts "              //   _ _   _ _   _ _   _ _   _ _   _ ]]"
    puts "        ..___//                                    }}"
    puts "      //                                           ]]"
    puts "     // = = = = = = = = = = = = = = = = = = = = = = \\\\"
    puts "       --------              __-_ _-    _-___ _-    ]]"
    puts "               \\\\          //   \\\\     //   \\\\      ]]"
    puts "          \"_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"("
    puts "\n"
    sleep(0.6)
    puts "\e[H\e[2J"
    puts "\n"
    puts "\n"
    puts "          __   _           __   _              __   _"
    puts "        _(  )_( )_       _(  )_( )_          _(  )_( )_"
    puts "       (_   _    _)     (_   _    _)       (_   _    _)"
    puts "         (_) (__)         (_) (__)           (_) (__)"
    puts "\n"
    puts "\n                      #{message}"
    puts "\n"
    puts "\n"
    puts "               ,,=================================.."
    puts "              //   _ _   _ _   _ _   _ _   _ _   _ ]]"
    puts "        ..___//                                    }}"
    puts "      //                                           ]]"
    puts "     // = = = = = = = = = = = = = = = = = = = = = = \\\\"
    puts "       --------              __-_ _-    _-___ _-    ]]"
    puts "             \"_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"("
    puts "\n"
    sleep(0.6)
    puts "\e[H\e[2J"
    puts "\n"
    puts "\n"
    puts "          __   _           __   _              __   _"
    puts "        _(  )_( )_       _(  )_( )_          _(  )_( )_"
    puts "       (_   _    _)     (_   _    _)       (_   _    _)"
    puts "         (_) (__)         (_) (__)           (_) (__)"
    puts "\n"
    puts "\n                      #{message}"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "               ,,=================================.."
    puts "              //   _ _   _ _   _ _   _ _   _ _   _ ]]"
    puts "        ..___//                                    }}"
    puts "      //                                           ]]"
    puts "     // = = = = = = = = = = = = = = = = = = = = = = \\\\"
    puts "          \"_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"("
    puts "\n"
    sleep(0.6)
    puts "\e[H\e[2J"
    puts "\n"
    puts "\n"
    puts "          __   _           __   _              __   _"
    puts "        _(  )_( )_       _(  )_( )_          _(  )_( )_"
    puts "       (_   _    _)     (_   _    _)       (_   _    _)"
    puts "         (_) (__)         (_) (__)           (_) (__)"
    puts "\n"
    puts "\n                      #{message}"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "               ,,=================================.."
    puts "              //   _ _   _ _   _ _   _ _   _ _   _ ]]"
    puts "        ..___//                                    }}"
    puts "      //                                           ]]"
    puts "        \"_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"("
    puts "\n"
    sleep(0.6)
    puts "\e[H\e[2J"
    puts "\n"
    puts "\n"
    puts "          __   _           __   _              __   _"
    puts "        _(  )_( )_       _(  )_( )_          _(  )_( )_"
    puts "       (_   _    _)     (_   _    _)       (_   _    _)"
    puts "         (_) (__)         (_) (__)           (_) (__)"
    puts "\n"
    puts "\n                      #{message}"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "               ,,=================================.."
    puts "              //   _ _   _ _   _ _   _ _   _ _   _ ]]"
    puts "        ..___//                                    }}"
    puts "           \"_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"("
    puts "\n"
    sleep(0.6)
    puts "\e[H\e[2J"
    puts "\n"
    puts "\n"
    puts "          __   _           __   _              __   _"
    puts "        _(  )_( )_       _(  )_( )_          _(  )_( )_"
    puts "       (_   _    _)     (_   _    _)       (_   _    _)"
    puts "         (_) (__)         (_) (__)           (_) (__)"
    puts "\n"
    puts "\n                      #{message}"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "               ,,=================================.."
    puts "              //   _ _   _ _   _ _   _ _   _ _   _ ]]"
    puts "         \"_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"("
    puts "\n"
    sleep(0.6)
    puts "\e[H\e[2J"
    puts "\n"
    puts "\n"
    puts "          __   _           __   _              __   _"
    puts "        _(  )_( )_       _(  )_( )_          _(  )_( )_"
    puts "       (_   _    _)     (_   _    _)       (_   _    _)"
    puts "         (_) (__)         (_) (__)           (_) (__)"
    puts "\n"
    puts "\n                      #{message}"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "               ,,=================================.."
    puts "          \"_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"("
    puts "\n"
    sleep(0.6)
    puts "\e[H\e[2J"
    puts "\n"
    puts "\n"
    puts "          __   _           __   _              __   _"
    puts "        _(  )_( )_       _(  )_( )_          _(  )_( )_"
    puts "       (_   _    _)     (_   _    _)       (_   _    _)"
    puts "         (_) (__)         (_) (__)           (_) (__)"
    puts "\n"
    puts "\n                      #{message}"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "         \"_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"("
    puts "\n"
    sleep(0.6)
    puts "\e[H\e[2J"
    puts "\n"
    puts "\n"
    puts "          __   _           __   _              __   _"
    puts "        _(  )_( )_       _(  )_( )_          _(  )_( )_"
    puts "       (_   _    _)     (_   _    _)       (_   _    _)"
    puts "         (_) (__)         (_) (__)           (_) (__)"
    puts "\n"
    puts "\n                      #{message}"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "\n"
    puts "           \"_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"(_.~\"("
    puts "\n"
    sleep(2)
  end





end
